### ISSUE TITLE
[Bug] RandomUtils percentageChance method validation always fails

### ISSUE THREAD

**Issue by WakelessSloth56** [auioc/arnicalib-mcmod#2]
```
Caused by: java.lang.IllegalArgumentException: The left bound must be less than the right bound
        at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.12.0.jar%2318!/:3.12.0]
        at org.auioc.mods.arnicalib.utils.java.Validate.isBoundedInterval(Validate.java:143) ~[%2381!/:?]
        at org.auioc.mods.arnicalib.utils.java.Validate.isInCloseInterval(Validate.java:181) ~[%2381!/:?]
        at org.auioc.mods.arnicalib.utils.java.RandomUtils.percentageChance(RandomUtils.java:73) ~[%2381!/:?]
```

**Comment by WakelessSloth56** [comment]
https://github.com/auioc/arnicalib-mcmod/blob/0483f9ab69910f6df5b8400e4ba908390755665c/src/main/java/org/auioc/mods/arnicalib/utils/java/RandomUtils.java#L72-L80

https://github.com/auioc/arnicalib-mcmod/blob/0483f9ab69910f6df5b8400e4ba908390755665c/src/main/java/org/auioc/mods/arnicalib/utils/java/Validate.java#L180

`isInCloseInterval` method parameter order should be `left bound`, `right bound`, `value`.
