### ISSUE TITLE
[BUG] server fails to start

### ISSUE THREAD

**Issue by ibox233** [auioc/arnicalib-mcmod#6]
### Description

[main/FATAL] [mixin/]: Mixin apply failed arnicalib.mixin.json:server.MixinLootContext -> net.minecraft.world.level.storage.loot.LootContext: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field queriedLootTableId was not located in the target class net.minecraft.world.level.storage.loot.LootContext. Using refmap arnicalib.mixin-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field queriedLootTableId was not located in the target class net.minecraft.world.level.storage.loot.LootContext. Using refmap arnicalib.mixin-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:629) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:305) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar%235!/:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.storage.loot.entries.ComposableEntryContainer.<clinit>(ComposableEntryContainer.java:10) ~[server-1.18.2-20220404.173914-srg.jar%2347!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntries.<clinit>(LootPoolEntries.java:15) ~[server-1.18.2-20220404.173914-srg.jar%2347!/:?]
	at net.minecraft.core.Registry.m_206132_(Registry.java:218) ~[server-1.18.2-20220404.173914-srg.jar%2347!/:?]
	at net.minecraft.core.Registry.m_205989_(Registry.java:352) ~[server-1.18.2-20220404.173914-srg.jar%2347!/:?]
	at net.minecraft.core.Registry.m_206036_(Registry.java:300) ~[server-1.18.2-20220404.173914-srg.jar%2347!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:299) ~[server-1.18.2-20220404.173914-srg.jar%2347!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:49) ~[server-1.18.2-20220404.173914-srg.jar%2347!/:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-1.18.2-20220404.173914-srg.jar%2347!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.60.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

### Environment

minecraft version 1.18.2
forge version 40.1.60
java version 17.0.3 by Microsoft

### Reproduction steps

just put arnicalib alone in the mods folder and the server won't start.

**Comment by WakelessSloth56** [comment]
We could not reproduce the problem at this time, please provide `logs/debug.log` using [pastebin.com](https://pastebin.com).

**Comment by ibox233** [comment]
latest.log - https://pastebin.com/Pjx2s0fe
debug.log - https://pastebin.com/m6JYhN2R

**Comment by WakelessSloth56** [comment]
I found that the forge coremod is not loading correctly either:
```
[137月2022 15:01:10.166] [main/ERROR] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod coremods/field_to_method.js function flowing_fluid_block
java.lang.IllegalStateException: Field f_54689_ is not private and an instance field
```
Can the server start successfully without ArnicaLib?

**Comment by WakelessSloth56** [comment]
In addition, does this problem occur on the client?

**Comment by ibox233** [comment]
without any mod, forge coremod will also report an error, I don't know why, server starts fine without ArnicaLib.
ArnicaLib works fine in the client.

**Comment by lainio24** [comment]
Mixin reports `field queriedLootTableId was not located in the target class net.minecraft.world.level.storage.loot.LootContext`, normally, this field actually exists:
```
  private net.minecraft.resources.ResourceLocation queriedLootTableId;
    descriptor: Lnet/minecraft/resources/ResourceLocation;
    flags: (0x0002) ACC_PRIVATE
```
So can you provide your `LootContext.class` in folder `net\minecraft\world\level\storage\loot\` in `libraries\net\minecraftforge\forge\1.18.2-40.1.60\forge-1.18.2-40.1.60-server.jar`?

**Comment by ibox233** [comment]
关闭这个反馈吧，不是模组的问题，是forge server的安装问题导致的，非常抱歉误报了。
